log_file_path = '~/Code/storage/test_data/storage.log'

[states]

[states.test]
private_key_path = "~/Code/storage/test_data/keys/key.txt"
encrypted_path = "~/Code/storage/test_data/encrypted/"
decrypted_path = "~/Code/storage/test_data/decrypted/"

[states.test_with_pass]
private_key_path = "~/Code/storage/test_data/keys/key_with_pass.txt.age" # passhrase: charge-ketchup-wife-cause-sell-despair-brick-label-expire-section
encrypted_path = "~/Code/storage/test_data/encrypted/"
decrypted_path = "~/Code/storage/test_data/decrypted/"
